### test login at localhost
POST http://localhost:8080/boats/api/login
Content-Type: application/json
accept: application/json

{
  "username": "user_admin",
  "password": "DQ123456"
}

### test welcome message localhost
GET http://localhost:8080/boats/api/boat

### test welcome message deployed
GET https://dengamlegymnastiksal.dk/tomcat/boats/api/boat

### get owners from localhost
GET http://localhost:8080/boats/api/boat/owner
x-access-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyX2FkbWluIiwicm9sZXMiOiJhZG1pbix1c2VyIiwiZXhwIjoxNjcxNjU3MTQyLCJpYXQiOjE2NzE2NTUzNDIsImlzc3VlciI6InNlbWVzdGVyc3RhcnRjb2RlLWRhdDMiLCJ1c2VybmFtZSI6InVzZXJfYWRtaW4ifQ.sdhtBtl29PrE9oHfDf7VRYKDYWJHgDWR5lXqt-nKYdY

### get owners from deployed
GET https://dengamlegymnastiksal.dk/tomcat/boats/api/boat/owner

### populate db local
GET http://localhost:8080/boats/api/boat/populate

### get harbours from localhost
GET http://localhost:8080/boats/api/boat/harbour
#x-access-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyX2FkbWluIiwicm9sZXMiOiJhZG1pbix1c2VyIiwiZXhwIjoxNjcxNzM3NjcxLCJpYXQiOjE2NzE3MzU4NzEsImlzc3VlciI6InNlbWVzdGVyc3RhcnRjb2RlLWRhdDMiLCJ1c2VybmFtZSI6InVzZXJfYWRtaW4ifQ.cQQaQVlu3nUsZ7KzGx9ALanlLy3LWw2l9vo_r6TpNfU

### get harbours from deployed
GET https://dengamlegymnastiksal.dk/tomcat/boats/api/boat/harbour
#x-access-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyX2FkbWluIiwicm9sZXMiOiJhZG1pbix1c2VyIiwiZXhwIjoxNjcxNzM3NjcxLCJpYXQiOjE2NzE3MzU4NzEsImlzc3VlciI6InNlbWVzdGVyc3RhcnRjb2RlLWRhdDMiLCJ1c2VybmFtZSI6InVzZXJfYWRtaW4ifQ.cQQaQVlu3nUsZ7KzGx9ALanlLy3LWw2l9vo_r6TpNfU

### get boats from localhost
GET http://localhost:8080/boats/api/boat/boat
x-access-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyX2FkbWluIiwicm9sZXMiOiJhZG1pbix1c2VyIiwiZXhwIjoxNjcxNzM3NjcxLCJpYXQiOjE2NzE3MzU4NzEsImlzc3VlciI6InNlbWVzdGVyc3RhcnRjb2RlLWRhdDMiLCJ1c2VybmFtZSI6InVzZXJfYWRtaW4ifQ.cQQaQVlu3nUsZ7KzGx9ALanlLy3LWw2l9vo_r6TpNfU


### get boats from deployed
GET https://dengamlegymnastiksal.dk/tomcat/boats/api/boat/boat
x-access-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyX2FkbWluIiwicm9sZXMiOiJhZG1pbix1c2VyIiwiZXhwIjoxNjcxNzM3NjcxLCJpYXQiOjE2NzE3MzU4NzEsImlzc3VlciI6InNlbWVzdGVyc3RhcnRjb2RlLWRhdDMiLCJ1c2VybmFtZSI6InVzZXJfYWRtaW4ifQ.cQQaQVlu3nUsZ7KzGx9ALanlLy3LWw2l9vo_r6TpNfU


### create new boat localhost
POST http://localhost:8080/boats/api/boat/boat
Content-Type: application/json
accept: application/json

{
  "brand": "Speeder17",
  "model": "luxus",
  "name": "Postspeederen2",
  "image": "https://pionerboat.com/wp-content/uploads/2022/05/Pioner15_Product_image_shop_nov2021.jpg",
  "harbour": {
    "id": 1,
    "name": "Melsted Havn",
    "address": "Melsted byvej",
    "capacity": 8
  }
}

### create new boat deployed
POST https://dengamlegymnastiksal.dk/tomcat/boats/api/boat/boat
Content-Type: application/json
accept: application/json

{
  "brand": "Speeder3",
  "model": "luxus2",
  "name": "Postspeederen2",
  "image": "https://pionerboat.com/wp-content/uploads/2022/05/Pioner15_Product_image_shop_nov2021.jpg",
  "harbourDTO": {
    "id": 1,
    "name": "Melsted Havn",
    "address": "Melsted byvej",
    "capacity": 8
  }
}

### edit boat localhost
PUT http://localhost:8080/boats/api/boat/boat/9
Content-Type: application/json
accept: application/json

{
  "id": "3",
  "brand": "Torpedobåd",
  "model": "luxus",
  "name": "Postspeederen2",
  "image": "https://pionerboat.com/wp-content/uploads/2022/05/Pioner15_Product_image_shop_nov2021.jpg",
  "harbour": {
    "id": 2,
    "name": "Melsted Havn",
    "address": "Melsted byvej",
    "capacity": 8
  },
  "owners": [
    {
      "id": 1,
      "name": "Skipper Bente",
      "address": "Persillehaven 38",
      "phone": "40404040"

    },
    {
      "id": 2,
      "name": "Skipper Bænt",
      "address": "Persillehaven 40",
      "phone": "38383838"
    }
  ]
}